using System;

namespace FSBANKLOL;

[Flags]
public enum BUILDFLAGS : uint
{
	BUILD_DEFAULT = 0u,
	BUILD_DISABLESYNCPOINTS = 1u,
	BUILD_DONTLOOP = 2u,
	BUILD_FILTERHIGHFREQ = 4u,
	BUILD_DISABLESEEKING = 8u,
	BUILD_OPTIMIZESAMPLERATE = 0x10u,
	BUILD_FSB5_DONTWRITENAMES = 0x80u,
	BUILD_NOGUID = 0x100u,
	BUILD_WRITEPEAKVOLUME = 0x200u
}
