namespace FSBANKLOL;

public enum FORMAT
{
	FSBANK_FORMAT_PCM,
	FSBANK_FORMAT_PCM_BIGENDIAN,
	FSBANK_FORMAT_XMA,
	FSBANK_FORMAT_AT9_PSVITA,
	FSBANK_FORMAT_AT9_PS4,
	FSBANK_FORMAT_VORBIS,
	FSBANK_FORMAT_FADPCM,
	FSBANK_FORMAT_MAX
}
