using System;

namespace FSBANKLOL;

[Flags]
public enum INITFLAGS : uint
{
	INIT_NORMAL = 0u,
	INIT_IGNOREERRORS = 1u,
	INIT_WARNINGSASERRORS = 2u,
	INIT_CREATEINCLUDEHEADER = 4u,
	INIT_DONTLOADCACHEFILES = 8u,
	INIT_GENERATEPROGRESSITEMS = 0x10u
}
