namespace FSBANKLOL;

public enum STATE
{
	FSBANK_STATE_DECODING,
	FSBANK_STATE_ANALYSING,
	FSBANK_STATE_PREPROCESSING,
	FSBANK_STATE_ENCODING,
	FSBANK_STATE_WRITING,
	FSBANK_STATE_FINISHED,
	FSBANK_STATE_FAILED,
	FSBANK_STATE_WARNING
}
